# Generated by Django 3.1.1 on 2020-09-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200901_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
